name: PraticFitBackend
description: Backend for Pratic Fit App
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  mongo_dart: ^0.8.2
  shelf: ^1.4.0
  shelf_modular: ^2.1.0
  shelf_router: ^1.1.3
  shelf_hotreload: ^1.4.0
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
