openapi: 3.0.0
info:
  description: "Backend API for Pratic Fit App"
  version: "0.1.0.1"
  title: "Pratic Fit Backend"
servers:
  - url: http://localhost:22669
    description: Local server
  - url: http://191.252.195.175:22669
    description: Remote server

paths:
  # Get all users
  /user:
    get:
      tags:
        - "User"
      summary: Get all users
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetAllUsersResponse"
        "400":
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackendException"
    # Create a new user
    post:
      tags:
        - "User"
      summary: "Create a new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
        description: "User object that needs to be added"
        required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserResponse"
        "400":
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackendException"
  # Get user by id
  /user/{id}:
    get:
      tags:
        - "User"
      summary: "Get user by id"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserByIdResponse"
        "400":
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackendException"
    # Update user by id and password
    put:
      tags:
        - "User"
      summary: "Update user by id and password"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserById"
        description: "User object that needs to be updated"
        required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateUserByIdResponse"
        "400":
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackendException"
    # Delete user by id and password
    delete:
      tags:
        - "User"
      summary: "Delete user by id and password"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteUserById"
        description: "User object that needs to be deleted"
        required: true
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteUserByIdResponse"
        "400":
          description: "Invalid status value"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackendException"

components:
  schemas:
    # Get all users response
    GetAllUsersResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    # Get user by id response
    GetUserByIdResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    # Create user
    CreateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
    # Create user response
    CreateUserResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    # Update user by id and password
    UpdateUserById:
      type: object
      properties:
        id:
          type: integer
        password:
          type: string
    # Update user by id response
    UpdateUserByIdResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    # Delete user by id and password
    DeleteUserById:
      type: object
      properties:
        id:
          type: integer
        password:
          type: string
    # Delete user by id response
    DeleteUserByIdResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    BackendException:
      type: object
      properties:
        error:
          type: string
