name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get -y install lftp

      - name: Upload files to FTP server
        env:
          FTP_USERNAME: ${{ secrets.ftp_username }}
          FTP_PASSWORD: ${{ secrets.ftp_password }}
          FTP_SERVER: ${{ secrets.ftp_server }}
        run: lftp -c "set ftp:ssl-allow true; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror --reverse --no-perms . /PraticFitBackend -e;"
